apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ei0t
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ei0t
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ei0t
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ei0t
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ei0t
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vjiz-tenant/rhtap-demo-app/hacbs-test-project-ei0t@sha256:c19594b163e4b9c6e3d89da3eefdf989a84ba09d5a3d590ff947327d8ef8eb4f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
