apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ei0t
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vjiz-tenant/rhtap-demo-app/hacbs-test-project-ei0t@sha256:c19594b163e4b9c6e3d89da3eefdf989a84ba09d5a3d590ff947327d8ef8eb4f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
